### PR TITLE
[WIP] Responsiveness

### PR DESCRIPTION
**Pull request by troubalex**
#13

### Current status
- Layout works nicely on smaller screens now
- I added two breakpoints: one for displays < 1040px and one for mobile devices
- I decided to hide the About blurb once the first breakpoint kicks in
- The overview panel still needs some extra love on the smallest screens
- All other elements are still visible, I'll hide them in my next commit

I decided to only focus on the layout for this pull-request, I might send another one that adjusts elements such as the buttons to touch screens.

### Screenshots

screenshot-2017-10-30 3d io modify 3d data 1

screenshot-2017-10-30 3d io modify 3d data 2

screenshot-2017-10-30 3d io modify 3d data 3

### CODE REVIEW

**Comment by Aadjou** [comment]
Screenshots look awedome already! Thank you!

**Comment by Aadjou** [comment]
Firefox vs chrome is doing weird things. 
Anyway, looks great, I will add some css to hide code and email information when logged in already. Looking forward to the prettifying

Thank you!

screen shot 2017-10-31 at 10 31 59

**Comment by troubalex** [comment]
I'll send another PR later today with the cleaned up blue bar on the top, and fix the browser issue. I'm half way there already.

Thanks for merging so quickly!

**Comment by Aadjou** [comment]
ah that's amazing!
please checkout my commit 3e07421 and feel free to improve it (my css skills are not so great)

**Pull request merged**
